version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    restart: always

volumes:
    mongodb:
    mongodb_config:
